name = "loke-jinks"
main = "src/index.ts"
compatibility_date = "2024-09-23"
workers_dev = false

routes = [
  { pattern = "lokejinks.tewodros.me", custom_domain = true }
]

# To set up your own KV namespace:
#   npx wrangler kv namespace create JOKES
#   npx wrangler kv namespace create JOKES --preview
# Then replace the id and preview_id below with your values.

[[kv_namespaces]]
binding = "JOKES"
id = "29eb5d962ace49aaa5091fe23ec76fac"
preview_id = "23d14ca6f711414a97e732197c47b056"
